// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package api

const (
	BearerScopes bearerContextKey = "bearer.Scopes"
)

// Me defines model for Me.
type Me struct {
	ClerkUserId string `json:"clerk_user_id"`
	DisplayName string `json:"display_name"`
	UserId      string `json:"user_id"`
}

// bearerContextKey is the context key for bearer security scheme
type bearerContextKey string
