// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package server

// Defines values for HealthStatus.
const (
	HealthStatusOk HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case HealthStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for ReadyFailedStatus.
const (
	ReadyFailedStatusNotReady ReadyFailedStatus = "not_ready"
)

// Valid indicates whether the value is a known member of the ReadyFailedStatus enum.
func (e ReadyFailedStatus) Valid() bool {
	switch e {
	case ReadyFailedStatusNotReady:
		return true
	default:
		return false
	}
}

// Defines values for ReadyOkStatus.
const (
	ReadyOkStatusReady ReadyOkStatus = "ready"
)

// Valid indicates whether the value is a known member of the ReadyOkStatus enum.
func (e ReadyOkStatus) Valid() bool {
	switch e {
	case ReadyOkStatusReady:
		return true
	default:
		return false
	}
}

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// Health defines model for Health.
type Health struct {
	Status HealthStatus `json:"status"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// ReadinessCheck defines model for ReadinessCheck.
type ReadinessCheck struct {
	Name string `json:"name"`
	Ok   bool   `json:"ok"`
}

// ReadyFailed defines model for ReadyFailed.
type ReadyFailed struct {
	Checks []ReadinessCheck  `json:"checks"`
	Status ReadyFailedStatus `json:"status"`
}

// ReadyFailedStatus defines model for ReadyFailed.Status.
type ReadyFailedStatus string

// ReadyOk defines model for ReadyOk.
type ReadyOk struct {
	Checks []ReadinessCheck `json:"checks"`
	Status ReadyOkStatus    `json:"status"`
}

// ReadyOkStatus defines model for ReadyOk.Status.
type ReadyOkStatus string

// bearerContextKey is the context key for bearer security scheme
type bearerContextKey string
