// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: designs.sql

package q

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteDesignUsages = `-- name: DeleteDesignUsages :exec
DELETE FROM design_material_usages
WHERE design_id = $1
`

func (q *Queries) DeleteDesignUsages(ctx context.Context, designID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDesignUsages, designID)
	return err
}

const getLiveDesign = `-- name: GetLiveDesign :one
SELECT id, owner_id, name, description, schema_version, document, version, copied_from_design_id, copied_from_pattern_id, created_at, updated_at, deleted_at
FROM designs
WHERE id = $1
  AND owner_id = $2
  AND deleted_at IS NULL
`

type GetLiveDesignParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

func (q *Queries) GetLiveDesign(ctx context.Context, arg GetLiveDesignParams) (Design, error) {
	row := q.db.QueryRow(ctx, getLiveDesign, arg.ID, arg.OwnerID)
	var i Design
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.SchemaVersion,
		&i.Document,
		&i.Version,
		&i.CopiedFromDesignID,
		&i.CopiedFromPatternID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertCopiedDesign = `-- name: InsertCopiedDesign :one
INSERT INTO designs (
    owner_id,
    name,
    description,
    schema_version,
    document,
    copied_from_design_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, owner_id, name, description, schema_version, document, version, copied_from_design_id, copied_from_pattern_id, created_at, updated_at, deleted_at
`

type InsertCopiedDesignParams struct {
	OwnerID            pgtype.UUID
	Name               string
	Description        string
	SchemaVersion      int32
	Document           json.RawMessage
	CopiedFromDesignID pgtype.UUID
}

func (q *Queries) InsertCopiedDesign(ctx context.Context, arg InsertCopiedDesignParams) (Design, error) {
	row := q.db.QueryRow(ctx, insertCopiedDesign,
		arg.OwnerID,
		arg.Name,
		arg.Description,
		arg.SchemaVersion,
		arg.Document,
		arg.CopiedFromDesignID,
	)
	var i Design
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.SchemaVersion,
		&i.Document,
		&i.Version,
		&i.CopiedFromDesignID,
		&i.CopiedFromPatternID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertDesign = `-- name: InsertDesign :one
INSERT INTO designs (
    owner_id,
    name,
    description,
    schema_version,
    document
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, owner_id, name, description, schema_version, document, version, copied_from_design_id, copied_from_pattern_id, created_at, updated_at, deleted_at
`

type InsertDesignParams struct {
	OwnerID       pgtype.UUID
	Name          string
	Description   string
	SchemaVersion int32
	Document      json.RawMessage
}

func (q *Queries) InsertDesign(ctx context.Context, arg InsertDesignParams) (Design, error) {
	row := q.db.QueryRow(ctx, insertDesign,
		arg.OwnerID,
		arg.Name,
		arg.Description,
		arg.SchemaVersion,
		arg.Document,
	)
	var i Design
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.SchemaVersion,
		&i.Document,
		&i.Version,
		&i.CopiedFromDesignID,
		&i.CopiedFromPatternID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertDesignUsage = `-- name: InsertDesignUsage :exec
INSERT INTO design_material_usages (design_id, material_id)
VALUES ($1, $2)
`

type InsertDesignUsageParams struct {
	DesignID   pgtype.UUID
	MaterialID pgtype.UUID
}

func (q *Queries) InsertDesignUsage(ctx context.Context, arg InsertDesignUsageParams) error {
	_, err := q.db.Exec(ctx, insertDesignUsage, arg.DesignID, arg.MaterialID)
	return err
}

const listLiveDesigns = `-- name: ListLiveDesigns :many
SELECT id, name, description, version, updated_at
FROM designs
WHERE owner_id = $1
  AND deleted_at IS NULL
ORDER BY updated_at DESC, id DESC
`

type ListLiveDesignsRow struct {
	ID          pgtype.UUID
	Name        string
	Description string
	Version     int32
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) ListLiveDesigns(ctx context.Context, ownerID pgtype.UUID) ([]ListLiveDesignsRow, error) {
	rows, err := q.db.Query(ctx, listLiveDesigns, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLiveDesignsRow
	for rows.Next() {
		var i ListLiveDesignsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Version,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockLiveDesign = `-- name: LockLiveDesign :one
SELECT id, owner_id, name, description, schema_version, document, version, copied_from_design_id, copied_from_pattern_id, created_at, updated_at, deleted_at
FROM designs
WHERE id = $1
  AND owner_id = $2
  AND deleted_at IS NULL
FOR UPDATE
`

type LockLiveDesignParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

func (q *Queries) LockLiveDesign(ctx context.Context, arg LockLiveDesignParams) (Design, error) {
	row := q.db.QueryRow(ctx, lockLiveDesign, arg.ID, arg.OwnerID)
	var i Design
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.SchemaVersion,
		&i.Document,
		&i.Version,
		&i.CopiedFromDesignID,
		&i.CopiedFromPatternID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteDesign = `-- name: SoftDeleteDesign :execrows
UPDATE designs
SET deleted_at = now(),
    updated_at = now()
WHERE id = $1
  AND owner_id = $2
  AND deleted_at IS NULL
`

type SoftDeleteDesignParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

func (q *Queries) SoftDeleteDesign(ctx context.Context, arg SoftDeleteDesignParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteDesign, arg.ID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateLiveDesign = `-- name: UpdateLiveDesign :one
UPDATE designs
SET
    name = $1,
    description = $2,
    document = $3,
    schema_version = $4,
    version = version + 1,
    updated_at = now()
WHERE id = $5
  AND owner_id = $6
  AND deleted_at IS NULL
RETURNING id, owner_id, name, description, schema_version, document, version, copied_from_design_id, copied_from_pattern_id, created_at, updated_at, deleted_at
`

type UpdateLiveDesignParams struct {
	Name          string
	Description   string
	Document      json.RawMessage
	SchemaVersion int32
	ID            pgtype.UUID
	OwnerID       pgtype.UUID
}

func (q *Queries) UpdateLiveDesign(ctx context.Context, arg UpdateLiveDesignParams) (Design, error) {
	row := q.db.QueryRow(ctx, updateLiveDesign,
		arg.Name,
		arg.Description,
		arg.Document,
		arg.SchemaVersion,
		arg.ID,
		arg.OwnerID,
	)
	var i Design
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.SchemaVersion,
		&i.Document,
		&i.Version,
		&i.CopiedFromDesignID,
		&i.CopiedFromPatternID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
