/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/designs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listDesigns"];
        put?: never;
        post: operations["createDesign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/designs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get: operations["getDesign"];
        put: operations["replaceDesign"];
        post?: never;
        delete: operations["deleteDesign"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @enum {string} */
            status: "ok";
        };
        ReadyOk: {
            /** @enum {string} */
            status: "ready";
            checks: components["schemas"]["ReadinessCheck"][];
        };
        ReadyFailed: {
            /** @enum {string} */
            status: "not_ready";
            checks: components["schemas"]["ReadinessCheck"][];
        };
        ReadinessCheck: {
            name: string;
            ok: boolean;
        };
        Error: {
            error: string;
        };
        Me: {
            user_id: string;
            clerk_user_id: string;
            display_name: string;
        };
        CreateDesignRequest: {
            /** @description The server removes leading and trailing whitespace. A blank result is rejected. */
            name: string;
            description?: string;
            document?: components["schemas"]["DesignDocument"];
        };
        ReplaceDesignRequest: {
            /** @description The server removes leading and trailing whitespace. A blank result is rejected. */
            name: string;
            description?: string;
            document: components["schemas"]["DesignDocument"];
        };
        DesignSummary: {
            /** Format: uuid */
            id: string;
            name: string;
            description: string;
            version: number;
            /** Format: date-time */
            updatedAt: string;
        };
        Design: {
            /** Format: uuid */
            id: string;
            name: string;
            description: string;
            version: number;
            /** Format: date-time */
            updatedAt: string;
            document: components["schemas"]["DesignDocument"];
        };
        /** @description A design at schema version 1. Lengths are inches. Rotation is Euler XYZ in degrees. */
        DesignDocument: {
            /** @enum {integer} */
            schemaVersion: 1;
            /** @enum {string} */
            units: "in";
            pieces: components["schemas"]["DesignPiece"][];
            connections: components["schemas"]["DesignConnection"][];
        };
        DesignPiece: {
            id: components["schemas"]["DocumentUuid"];
            name: string;
            materialId: components["schemas"]["DocumentUuid"];
            /** @default false */
            roughCut: boolean;
            /** @description Exact inch length. The numeric value stays exact. An exponent form can come back as a plain decimal. */
            lengthIn: number;
            continuity: components["schemas"]["DesignContinuity"];
            transform: components["schemas"]["DesignTransform"];
        };
        /** @description One flag per local axis. True means that axis stays one board. False means the solver may splice. */
        DesignContinuity: {
            x: boolean;
            y: boolean;
            z: boolean;
        };
        DesignTransform: {
            /** @description Inches, in axis order x, y, z. */
            positionIn: number[];
            /** @description Euler angles in degrees, applied in X, then Y, then Z order. */
            rotationDeg: number[];
        };
        DesignConnection: {
            id: string;
            pieceAId: components["schemas"]["DocumentUuid"];
            pieceBId: components["schemas"]["DocumentUuid"];
            /** @enum {string} */
            joinType: "butt" | "lap" | "fastener";
            faceA: string;
            faceB: string;
            /** @description Exact inches. The numeric value stays exact. An exponent form can come back as a plain decimal. */
            wasteIn: number;
        };
        /**
         * Format: uuid
         * @description A client-generated UUID. Unique among piece ids in one document. It is not a database key.
         */
        DocumentUuid: string;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The process is up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description The process panicked. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every probe succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyOk"];
                };
            };
            /** @description The process panicked. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description A probe failed. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyFailed"];
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The signed-in user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description The request has no valid session. */
            401: {
                headers: {
                    "WWW-Authenticate": "Bearer";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The session check or the user row failed. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listDesigns: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's live designs, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DesignSummary"][];
                };
            };
            /** @description The request has no valid session. */
            401: {
                headers: {
                    "WWW-Authenticate": "Bearer";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The designs were not loaded. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createDesign: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDesignRequest"];
            };
        };
        responses: {
            /** @description The design was created. */
            201: {
                headers: {
                    Location: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Design"];
                };
            };
            /** @description The name or the document is not valid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The request has no valid session. */
            401: {
                headers: {
                    "WWW-Authenticate": "Bearer";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The document names a material that does not exist. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The design was not saved. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getDesign: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The design, including its document. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Design"];
                };
            };
            /** @description The request has no valid session. */
            401: {
                headers: {
                    "WWW-Authenticate": "Bearer";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The caller has no such design. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The design was not loaded. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    replaceDesign: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplaceDesignRequest"];
            };
        };
        responses: {
            /** @description The design was replaced. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Design"];
                };
            };
            /** @description The name or the document is not valid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The request has no valid session. */
            401: {
                headers: {
                    "WWW-Authenticate": "Bearer";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The caller has no such design. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The document names a material that does not exist. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The design was not saved. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deleteDesign: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The design was deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The request has no valid session. */
            401: {
                headers: {
                    "WWW-Authenticate": "Bearer";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The caller has no such design. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The design was not deleted. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
